version: "3"
services:

  db:
    build: ./db
    environment:
      - MYSQL_DATABASE=auditoria
      - MYSQL_USER=performance
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    command: "mysqld --max_connections=100000 --connect-timeout=31536000 --max-prepared-stmt-count=1048576"
    depends_on:
      - tomcat
  tomcat:
    build: .
    ports:
      - "8080:8080"
    
